apiVersion: v1
kind: Pod
metadata:
  name: hello-app-pod1
  labels:
    name: hello-app-pod1
    app: demo-hello-app1
spec:
  containers:
  - name: hello-app1
    image: yousefgadbandocker/hello1:1.1
    ports:
    - containerPort: 5021
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service1
  labels:
    name: hello-service1
    app: demo-hello-app1
spec:
  type: LoadBalancer
  ports:
  - port: 5021
    targetPort: 5021
  selector:
    name: hello-app-pod1
    app: demo-hello-app1

