apiVersion: apps/v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    name: hello-pod
    app: demo-hello-app
spec:
  contailners:
  - name: hello-app
    image: codewithmosh/hello-docker
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    name: hello-service
    app: demo-hello-app
spec:
  type: LoadBalancer
  ports:
    port: 80
    targetPort: 80
  selector:
    name: hello-pod
    app: demo-hello-app

