apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:5.0
        # command:
        #   - mongod
        #   - "--replSet"
        #   - rs0
        #   - "--smallfiles"
        #   - "--noprealloc"
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: pvc
            mountPath: /data/db
      # - name: mongo-sidecar
      #   image: cvallance/mongo-k8s-sidecar
      #   env:
      #     - name: MONGO_SIDECAR_POD_LABELS
      #       value: "role=mongo,environment=test"
  volumeClaimTemplates:
    - metadata:
        name: pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
